// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using ContentAuthenticity.Schema.Builder;
//
//    var manifestDefinition = ManifestDefinition.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace ContentAuthenticity.Schema.Builder
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Use a ManifestDefinition to define a manifest and to build a `ManifestStore`.
    /// A manifest is a collection of ingredients and assertions
    /// used to define a claim that can be signed and embedded into a file.
    /// </summary>
    public partial class ManifestDefinition
    {
        /// <summary>
        /// A list of assertions
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("assertions")]
        public AssertionElement[]? Assertions { get; set; }

        /// <summary>
        /// Software that generated the claim, as a list of [`ClaimGeneratorInfo`].
        ///
        /// In JSON, when this key is **omitted** (or the array is empty), the value is
        /// resolved at claim-building time: settings.builder.claim_generator_info if set, otherwise
        /// on the active [`Context`] is used if set, otherwise [`ClaimGeneratorInfo::default`].
        /// A non-empty list in the definition is used as given.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("claim_generator_info")]
        public ClaimGeneratorInfoElement[]? ClaimGeneratorInfo { get; set; }

        /// <summary>
        /// The version of the claim.  Defaults to 2.
        /// </summary>
        [JsonPropertyName("claim_version")]
        public long? ClaimVersion { get; set; }

        /// <summary>
        /// The format of the source file as a MIME type.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("format")]
        public string? Format { get; set; }

        /// <summary>
        /// Hash algorithm used for asset hashing (DataHash, BmffHash) and assertion hashing
        /// in the claim.  Defaults to `"sha256"` when not set.
        ///
        /// Valid values: `"sha256"`, `"sha384"`, `"sha512"`.
        ///
        /// This sets the claim-level `alg` field and is the default used by
        /// [`Builder::update_hash_from_stream`].  It can be overridden on individual
        /// hard binding assertions (e.g. a pre-constructed `DataHash`) by setting
        /// the assertion's own `alg` field before adding it to the builder.
        ///
        /// Named `hash_alg` (rather than `alg`) to avoid collision with the signer's
        /// signature algorithm, which uses the same key in some combined JSON configurations.
        /// </summary>
        [JsonPropertyName("hash_alg")]
        public string? HashAlg { get; set; }

        /// <summary>
        /// A List of ingredients
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ingredients")]
        public IngredientElement[]? Ingredients { get; set; }

        /// <summary>
        /// Instance ID from `xmpMM:InstanceID` in XMP metadata.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instance_id")]
        public string? InstanceId { get; set; }

        /// <summary>
        /// Allows you to pre-define the manifest label, which must be unique.
        /// Not intended for general use.  If not set, it will be assigned automatically.
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get; set; }

        /// <summary>
        /// Optional manifest metadata. This will be deprecated in the future; not recommended to use.
        /// </summary>
        [JsonPropertyName("metadata")]
        public MetadatumElement[]? Metadata { get; set; }

        /// <summary>
        /// JUMBF URIs of assertions to redact from ingredient manifests.
        ///
        /// Each URI has the form
        /// `self#jumbf=/c2pa/&lt;manifest_label&gt;/c2pa.assertions/&lt;assertion_label&gt;`.
        /// Use a [`Reader`](crate::Reader) to discover the manifest label.
        /// See the [redaction
        /// guide](https://github.com/contentauth/c2pa-rs/blob/main/docs/redaction.md)
        /// for details.
        /// </summary>
        [JsonPropertyName("redactions")]
        public string[]? Redactions { get; set; }

        /// <summary>
        /// An optional ResourceRef to a thumbnail image that represents the asset that was signed.
        /// Must be available when the manifest is signed.
        /// </summary>
        [JsonPropertyName("thumbnail")]
        public ThumbnailClass? Thumbnail { get; set; }

        /// <summary>
        /// A human-readable title, generally source filename.
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Optional prefix added to the generated Manifest Label
        /// This is typically a reverse domain name.
        /// </summary>
        [JsonPropertyName("vendor")]
        public string? Vendor { get; set; }
    }

    /// <summary>
    /// Defines an assertion that consists of a label that can be either
    /// a C2PA-defined assertion label or a custom label in reverse domain format.
    /// </summary>
    public partial class AssertionElement
    {
        /// <summary>
        /// True if this assertion is attributed to the signer (defaults to false)
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("created")]
        public bool? Created { get; set; }

        /// <summary>
        /// The assertion data
        /// </summary>
        [JsonPropertyName("data")]
        public object Data { get; set; }

        /// <summary>
        /// The kind of assertion data, either Cbor or Json (defaults to Cbor)
        /// </summary>
        [JsonPropertyName("kind")]
        public KindEnum? Kind { get; set; }

        /// <summary>
        /// An assertion label in reverse domain format
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get; set; }
    }

    /// <summary>
    /// Description of the claim generator, or the software used in generating the claim.
    ///
    /// This structure is also used for actions softwareAgent
    /// </summary>
    public partial class ClaimGeneratorInfoElement
    {
        /// <summary>
        /// hashed URI to the icon (either embedded or remote)
        /// </summary>
        [JsonPropertyName("icon")]
        public IconClass? Icon { get; set; }

        /// <summary>
        /// A human readable string naming the claim_generator
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// A human readable string of the OS the claim generator is running on.
        /// CrJSON schema uses `operating_system`; C2PA CBOR may use
        /// `schema.org.SoftwareApplication.operatingSystem`.
        /// </summary>
        [JsonPropertyName("operating_system")]
        public string? OperatingSystem { get; set; }

        /// <summary>
        /// A human readable string of the product's version
        /// </summary>
        [JsonPropertyName("version")]
        public string? Version { get; set; }
    }

    /// <summary>
    /// A reference to a resource to be used in JSON serialization.
    ///
    /// The underlying data can be read as a stream via
    /// [`Reader::resource_to_stream`][crate::Reader::resource_to_stream].
    ///
    /// A `HashedUri` provides a reference to content available within the same
    /// manifest store.
    ///
    /// This is described in [URI References in the C2PA Technical
    ///
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_uri_references).
    /// </summary>
    public partial class IconClass
    {
        /// <summary>
        /// The algorithm used to hash the resource (if applicable).
        ///
        /// A string identifying the cryptographic hash algorithm used to compute
        /// the hash
        /// </summary>
        [JsonPropertyName("alg")]
        public string? Alg { get; set; }

        /// <summary>
        /// More detailed data types as defined in the C2PA spec.
        /// </summary>
        [JsonPropertyName("data_types")]
        public DataTypeElement[]? DataTypes { get; set; }

        /// <summary>
        /// The mime type of the referenced resource.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("format")]
        public string? Format { get; set; }

        /// <summary>
        /// The hash of the resource (if applicable).
        ///
        /// Byte string containing the hash value
        /// </summary>
        [JsonPropertyName("hash")]
        public Alg? Hash { get; set; }

        /// <summary>
        /// A URI that identifies the resource as referenced from the manifest.
        ///
        /// This may be a JUMBF URI, a file path, a URL or any other string.
        /// Relative JUMBF URIs will be resolved with the manifest label.
        /// Relative file paths will be resolved with the base path if provided.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("identifier")]
        public string? Identifier { get; set; }

        /// <summary>
        /// JUMBF URI reference
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("url")]
        public string? Url { get; set; }
    }

    public partial class DataTypeElement
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("version")]
        public string? Version { get; set; }
    }

    /// <summary>
    /// An `Ingredient` is any external asset that has been used in the creation of an asset.
    /// </summary>
    public partial class IngredientElement
    {
        /// <summary>
        /// The active manifest label (if one exists).
        ///
        /// If this ingredient has a [`ManifestStore`],
        /// this will hold the label of the active [`Manifest`].
        ///
        /// [`Manifest`]: crate::Manifest
        /// [`ManifestStore`]: crate::ManifestStore
        /// </summary>
        [JsonPropertyName("active_manifest")]
        public string? ActiveManifest { get; set; }

        /// <summary>
        /// A reference to the actual data of the ingredient.
        /// </summary>
        [JsonPropertyName("data")]
        public ThumbnailClass? Data { get; set; }

        /// <summary>
        /// Additional information about the data's type to the ingredient V2 structure.
        /// </summary>
        [JsonPropertyName("data_types")]
        public DataTypeElement[]? DataTypes { get; set; }

        /// <summary>
        /// Additional description of the ingredient.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Document ID from `xmpMM:DocumentID` in XMP metadata.
        /// </summary>
        [JsonPropertyName("document_id")]
        public string? DocumentId { get; set; }

        /// <summary>
        /// The format of the source file as a MIME type.
        /// </summary>
        [JsonPropertyName("format")]
        public string? Format { get; set; }

        /// <summary>
        /// An optional hash of the asset to prevent duplicates.
        /// </summary>
        [JsonPropertyName("hash")]
        public string? Hash { get; set; }

        /// <summary>
        /// URI to an informational page about the ingredient or its data.
        /// </summary>
        [JsonPropertyName("informational_URI")]
        public string? InformationalUri { get; set; }

        /// <summary>
        /// Instance ID from `xmpMM:InstanceID` in XMP metadata.
        /// </summary>
        [JsonPropertyName("instance_id")]
        public string? InstanceId { get; set; }

        /// <summary>
        /// The ingredient's label as assigned in the manifest.
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get; set; }

        /// <summary>
        /// A [`ManifestStore`] from the source asset extracted as a binary C2PA blob.
        ///
        /// [`ManifestStore`]: crate::ManifestStore
        /// </summary>
        [JsonPropertyName("manifest_data")]
        public ThumbnailClass? ManifestData { get; set; }

        /// <summary>
        /// Any additional [`Metadata`] as defined in the C2PA spec.
        ///
        /// [`Metadata`]: crate::Metadata
        /// </summary>
        [JsonPropertyName("metadata")]
        public MetadatumElement? Metadata { get; set; }

        [JsonPropertyName("ocsp_responses")]
        public ThumbnailClass[]? OcspResponses { get; set; }

        /// <summary>
        /// URI from `dcterms:provenance` in XMP metadata.
        /// </summary>
        [JsonPropertyName("provenance")]
        public string? Provenance { get; set; }

        /// <summary>
        /// Set to `ParentOf` if this is the parent ingredient.
        ///
        /// There can only be one parent ingredient in the ingredients.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("relationship")]
        public Relationship? Relationship { get; set; }

        /// <summary>
        /// A thumbnail image capturing the visual state at the time of import.
        ///
        /// A tuple of thumbnail MIME format (for example `image/jpeg`) and binary bits of the image.
        /// </summary>
        [JsonPropertyName("thumbnail")]
        public ThumbnailClass? Thumbnail { get; set; }

        /// <summary>
        /// A human-readable title, generally source filename.
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Validation results (Ingredient.V3)
        /// </summary>
        [JsonPropertyName("validation_results")]
        public ValidationResultsClass? ValidationResults { get; set; }

        /// <summary>
        /// Validation status (Ingredient v1 &amp; v2)
        /// </summary>
        [JsonPropertyName("validation_status")]
        public ValidationStatusElement[]? ValidationStatus { get; set; }
    }

    /// <summary>
    /// A reference to a resource to be used in JSON serialization.
    ///
    /// The underlying data can be read as a stream via
    /// [`Reader::resource_to_stream`][crate::Reader::resource_to_stream].
    /// </summary>
    public partial class ThumbnailClass
    {
        /// <summary>
        /// The algorithm used to hash the resource (if applicable).
        /// </summary>
        [JsonPropertyName("alg")]
        public string? Alg { get; set; }

        /// <summary>
        /// More detailed data types as defined in the C2PA spec.
        /// </summary>
        [JsonPropertyName("data_types")]
        public DataTypeElement[]? DataTypes { get; set; }

        /// <summary>
        /// The mime type of the referenced resource.
        /// </summary>
        [JsonPropertyName("format")]
        public string Format { get; set; }

        /// <summary>
        /// The hash of the resource (if applicable).
        /// </summary>
        [JsonPropertyName("hash")]
        public string? Hash { get; set; }

        /// <summary>
        /// A URI that identifies the resource as referenced from the manifest.
        ///
        /// This may be a JUMBF URI, a file path, a URL or any other string.
        /// Relative JUMBF URIs will be resolved with the manifest label.
        /// Relative file paths will be resolved with the base path if provided.
        /// </summary>
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }
    }

    /// <summary>
    /// A region of interest within an asset describing the change.
    ///
    /// This struct can be used from [`Action::changes`][crate::assertions::Action::changes],
    ///
    /// [`AssertionMetadata::region_of_interest`][crate::assertions::AssertionMetadata::region_of_interest],
    /// or
    /// [`SoftBindingScope::region`][crate::assertions::soft_binding::SoftBindingScope::region].
    /// </summary>
    public partial class RegionOfInterestClass
    {
        /// <summary>
        /// A free-text string.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// A free-text string representing a machine-readable, unique to this assertion, identifier
        /// for the region.
        /// </summary>
        [JsonPropertyName("identifier")]
        public string? Identifier { get; set; }

        /// <summary>
        /// Additional information about the asset.
        /// </summary>
        [JsonPropertyName("metadata")]
        public MetadatumElement? Metadata { get; set; }

        /// <summary>
        /// A free-text string representing a human-readable name for the region which might be used
        /// in a user interface.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// A range describing the region of interest for the specific asset.
        /// </summary>
        [JsonPropertyName("region")]
        public RegionElement[] Region { get; set; }

        /// <summary>
        /// A value from our controlled vocabulary or an entity-specific value (e.g.,
        /// com.litware.coolArea) that represents
        /// the role of a region among other regions.
        /// </summary>
        [JsonPropertyName("role")]
        public RoleEnum? Role { get; set; }

        /// <summary>
        /// A value from a controlled vocabulary such as
        /// &lt;https://cv.iptc.org/newscodes/imageregiontype/&gt; or an entity-specific
        /// value (e.g., com.litware.newType) that represents the type of thing(s) depicted by a
        /// region.
        ///
        /// Note this field serializes/deserializes into the name `type`.
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }
    }

    /// <summary>
    /// The AssertionMetadata structure can be used as part of other assertions or on its own to
    /// reference others
    /// </summary>
    public partial class MetadatumElement
    {
        [JsonPropertyName("dataSource")]
        public DataSourceClass? DataSource { get; set; }

        [JsonPropertyName("dateTime")]
        public string? DateTime { get; set; }

        [JsonPropertyName("localizations")]
        public Dictionary<string, Dictionary<string, string>>[]? Localizations { get; set; }

        [JsonPropertyName("reference")]
        public ReferenceElement? Reference { get; set; }

        [JsonPropertyName("regionOfInterest")]
        public RegionOfInterestClass? RegionOfInterest { get; set; }

        [JsonPropertyName("reviewRatings")]
        public ReviewRatingElement[]? ReviewRatings { get; set; }
    }

    /// <summary>
    /// A spatial, temporal, frame, or textual range describing the region of interest.
    /// </summary>
    public partial class RegionElement
    {
        /// <summary>
        /// A frame range.
        /// </summary>
        [JsonPropertyName("frame")]
        public FrameClass? Frame { get; set; }

        /// <summary>
        /// A item identifier.
        /// </summary>
        [JsonPropertyName("item")]
        public ItemClass? Item { get; set; }

        /// <summary>
        /// A spatial range.
        /// </summary>
        [JsonPropertyName("shape")]
        public ShapeClass? Shape { get; set; }

        /// <summary>
        /// A textual range.
        /// </summary>
        [JsonPropertyName("text")]
        public TextClass? Text { get; set; }

        /// <summary>
        /// A temporal range.
        /// </summary>
        [JsonPropertyName("time")]
        public TimeClass? Time { get; set; }

        /// <summary>
        /// The type of range of interest.
        /// </summary>
        [JsonPropertyName("type")]
        public RegionType Type { get; set; }
    }

    /// <summary>
    /// A frame range representing starting and ending frames or pages.
    ///
    /// If both `start` and `end` are missing, the frame will span the entire asset.
    /// </summary>
    public partial class FrameClass
    {
        /// <summary>
        /// The end of the frame inclusive or the end of the asset if not present.
        /// </summary>
        [JsonPropertyName("end")]
        public long? End { get; set; }

        /// <summary>
        /// The start of the frame or the end of the asset if not present.
        ///
        /// The first frame/page starts at 0.
        /// </summary>
        [JsonPropertyName("start")]
        public long? Start { get; set; }
    }

    /// <summary>
    /// Description of the boundaries of an identified range.
    /// </summary>
    public partial class ItemClass
    {
        /// <summary>
        /// The container-specific term used to identify items, such as "track_id" for MP4 or
        /// "item_ID" for HEIF.
        /// </summary>
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// The value of the identifier, e.g. a value of "2" for an identifier of "track_id" would
        /// imply track 2 of the asset.
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }
    }

    /// <summary>
    /// A spatial range representing rectangle, circle, or a polygon.
    /// </summary>
    public partial class ShapeClass
    {
        /// <summary>
        /// The height of a rectnagle.
        ///
        /// This field can be ignored for circles and polygons.
        /// </summary>
        [JsonPropertyName("height")]
        public double? Height { get; set; }

        /// <summary>
        /// If the range is inside the shape.
        ///
        /// The default value is true.
        /// </summary>
        [JsonPropertyName("inside")]
        public bool? Inside { get; set; }

        /// <summary>
        /// THe origin of the coordinate in the shape.
        /// </summary>
        [JsonPropertyName("origin")]
        public Origin Origin { get; set; }

        /// <summary>
        /// The type of shape.
        /// </summary>
        [JsonPropertyName("type")]
        public ShapeType Type { get; set; }

        /// <summary>
        /// The type of unit for the shape range.
        /// </summary>
        [JsonPropertyName("unit")]
        public Unit Unit { get; set; }

        /// <summary>
        /// The vertices of the polygon.
        ///
        /// This field can be ignored for rectangles and circles.
        /// </summary>
        [JsonPropertyName("vertices")]
        public Origin[]? Vertices { get; set; }

        /// <summary>
        /// The width for rectangles or diameter for circles.
        ///
        /// This field can be ignored for polygons.
        /// </summary>
        [JsonPropertyName("width")]
        public double? Width { get; set; }
    }

    /// <summary>
    /// THe origin of the coordinate in the shape.
    ///
    /// An x, y coordinate used for specifying vertices in polygons.
    /// </summary>
    public partial class Origin
    {
        /// <summary>
        /// The coordinate along the x-axis.
        /// </summary>
        [JsonPropertyName("x")]
        public double X { get; set; }

        /// <summary>
        /// The coordinate along the y-axis.
        /// </summary>
        [JsonPropertyName("y")]
        public double Y { get; set; }
    }

    /// <summary>
    /// A textual range representing multiple (possibly discontinuous) ranges of text.
    /// </summary>
    public partial class TextClass
    {
        /// <summary>
        /// The ranges of text to select.
        /// </summary>
        [JsonPropertyName("selectors")]
        public SelectorElement[] Selectors { get; set; }
    }

    /// <summary>
    /// One or two [`TextSelector`] identifiying the range to select.
    /// </summary>
    public partial class SelectorElement
    {
        /// <summary>
        /// The end of the text range.
        /// </summary>
        [JsonPropertyName("end")]
        public EndClass? End { get; set; }

        /// <summary>
        /// The start (or entire) text range.
        /// </summary>
        [JsonPropertyName("selector")]
        public EndClass Selector { get; set; }
    }

    /// <summary>
    /// Selects a range of text via a fragment identifier.
    ///
    /// This is modeled after the W3C Web Annotation selector model.
    ///
    /// The start (or entire) text range.
    /// </summary>
    public partial class EndClass
    {
        /// <summary>
        /// The end character offset or the end of the fragment if not present.
        /// </summary>
        [JsonPropertyName("end")]
        public long? End { get; set; }

        /// <summary>
        /// Fragment identifier as per RFC3023 (XML) or ISO 32000-2 (PDF), Annex O.
        /// </summary>
        [JsonPropertyName("fragment")]
        public string Fragment { get; set; }

        /// <summary>
        /// The start character offset or the start of the fragment if not present.
        /// </summary>
        [JsonPropertyName("start")]
        public long? Start { get; set; }
    }

    /// <summary>
    /// A temporal range representing a starting time to an ending time.
    /// </summary>
    public partial class TimeClass
    {
        /// <summary>
        /// The end time or the end of the asset if not present.
        /// </summary>
        [JsonPropertyName("end")]
        public string? End { get; set; }

        /// <summary>
        /// The start time or the start of the asset if not present.
        /// </summary>
        [JsonPropertyName("start")]
        public string? Start { get; set; }

        /// <summary>
        /// The type of time.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("type")]
        public TimeType? Type { get; set; }
    }

    /// <summary>
    /// A description of the source for assertion data
    /// </summary>
    public partial class DataSourceClass
    {
        /// <summary>
        /// A list of [`Actor`]s associated with this source.
        /// </summary>
        [JsonPropertyName("actors")]
        public ActorElement[]? Actors { get; set; }

        /// <summary>
        /// A human-readable string giving details about the source of the assertion data.
        /// </summary>
        [JsonPropertyName("details")]
        public string? Details { get; set; }

        /// <summary>
        /// A value from among the enumerated list indicating the source of the assertion.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    /// <summary>
    /// Identifies a person responsible for an action.
    /// </summary>
    public partial class ActorElement
    {
        /// <summary>
        /// List of references to W3C Verifiable Credentials.
        /// </summary>
        [JsonPropertyName("credentials")]
        public ReferenceElement[]? Credentials { get; set; }

        /// <summary>
        /// An identifier for a human actor, used when the "type" is `humanEntry.identified`.
        /// </summary>
        [JsonPropertyName("identifier")]
        public string? Identifier { get; set; }
    }

    /// <summary>
    /// A `HashedUri` provides a reference to content available within the same
    /// manifest store.
    ///
    /// This is described in [URI References in the C2PA Technical
    ///
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_uri_references).
    /// </summary>
    public partial class ReferenceElement
    {
        /// <summary>
        /// A string identifying the cryptographic hash algorithm used to compute
        /// the hash
        /// </summary>
        [JsonPropertyName("alg")]
        public string? Alg { get; set; }

        /// <summary>
        /// Byte string containing the hash value
        /// </summary>
        [JsonPropertyName("hash")]
        public long[] Hash { get; set; }

        /// <summary>
        /// JUMBF URI reference
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }
    }

    /// <summary>
    /// A rating on an Assertion.
    ///
    /// See [C2PA Specification - Review
    /// Ratings](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_review_ratings).
    /// </summary>
    public partial class ReviewRatingElement
    {
        [JsonPropertyName("code")]
        public string? Code { get; set; }

        [JsonPropertyName("explanation")]
        public string Explanation { get; set; }

        [JsonPropertyName("value")]
        public long Value { get; set; }
    }

    /// <summary>
    /// A map of validation results for a manifest store.
    ///
    /// The map contains the validation results for the active manifest and any ingredient
    /// deltas.
    /// It is normal for there to be many
    /// </summary>
    public partial class ValidationResultsClass
    {
        /// <summary>
        /// Validation status codes for the ingredient's active manifest. Present if ingredient is a
        /// C2PA
        /// asset. Not present if the ingredient is not a C2PA asset.
        /// </summary>
        [JsonPropertyName("activeManifest")]
        public ActiveManifestClass? ActiveManifest { get; set; }

        /// <summary>
        /// List of any changes/deltas between the current and previous validation results for each
        /// ingredient's
        /// manifest. Present if the the ingredient is a C2PA asset.
        /// </summary>
        [JsonPropertyName("ingredientDeltas")]
        public IngredientDeltaElement[]? IngredientDeltas { get; set; }

        /// <summary>
        /// Time when the validation was performed (RFC 3339 date-time). Used only for document-level
        /// validationInfo; not serialized in validationResults (e.g. ingredient assertions).
        /// </summary>
        [JsonPropertyName("validationTime")]
        public string? ValidationTime { get; set; }
    }

    /// <summary>
    /// Contains a set of success, informational, and failure validation status codes.
    ///
    /// Validation results for the ingredient's active manifest
    /// </summary>
    public partial class ActiveManifestClass
    {
        /// <summary>
        /// An array of validation failure codes. May be empty.
        /// </summary>
        [JsonPropertyName("failure")]
        public ValidationStatusElement[] Failure { get; set; }

        /// <summary>
        /// An array of validation informational codes. May be empty.
        /// </summary>
        [JsonPropertyName("informational")]
        public ValidationStatusElement[] Informational { get; set; }

        /// <summary>
        /// An array of validation success codes. May be empty.
        /// </summary>
        [JsonPropertyName("success")]
        public ValidationStatusElement[] Success { get; set; }
    }

    /// <summary>
    /// A `ValidationStatus` struct describes the validation status of a
    /// specific part of a manifest.
    ///
    /// See [Existing Manifests - C2PA Technical
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_existing_manifests).
    /// </summary>
    public partial class ValidationStatusElement
    {
        [JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonPropertyName("explanation")]
        public string? Explanation { get; set; }

        [JsonPropertyName("success")]
        public bool? Success { get; set; }

        [JsonPropertyName("url")]
        public string? Url { get; set; }
    }

    /// <summary>
    /// Represents any changes or deltas between the current and previous validation results for
    /// an ingredient's manifest.
    /// </summary>
    public partial class IngredientDeltaElement
    {
        /// <summary>
        /// JUMBF URI reference to the ingredient assertion
        /// </summary>
        [JsonPropertyName("ingredientAssertionURI")]
        public string IngredientAssertionUri { get; set; }

        /// <summary>
        /// Validation results for the ingredient's active manifest
        /// </summary>
        [JsonPropertyName("validationDeltas")]
        public ActiveManifestClass ValidationDeltas { get; set; }
    }

    /// <summary>
    /// Assertions in C2PA can be stored in several formats
    /// </summary>
    public enum KindEnum { Binary, Cbor, Json, Uri };

    /// <summary>
    /// The type of shape.
    ///
    /// The type of shape for the range.
    ///
    /// A rectangle.
    ///
    /// A circle.
    ///
    /// A polygon.
    /// </summary>
    public enum ShapeType { Circle, Polygon, Rectangle };

    /// <summary>
    /// The type of unit for the shape range.
    ///
    /// The type of unit for the range.
    ///
    /// Use pixels.
    ///
    /// Use percentage.
    /// </summary>
    public enum Unit { Percent, Pixel };

    /// <summary>
    /// The type of time.
    ///
    /// Times are described using Normal Play Time (npt) as described in RFC 2326.
    /// </summary>
    public enum TimeType { Npt };

    /// <summary>
    /// The type of range of interest.
    ///
    /// The type of range for the region of interest.
    ///
    /// A spatial range, see [`Shape`] for more details.
    ///
    /// A temporal range, see [`Time`] for more details.
    ///
    /// A spatial range, see [`Frame`] for more details.
    ///
    /// A textual range, see [`Text`] for more details.
    ///
    /// A range identified by a specific identifier and value, see [`Item`] for more details.
    /// </summary>
    public enum RegionType { Frame, Identified, Spatial, Temporal, Textual };

    /// <summary>
    /// Arbitrary area worth identifying.
    ///
    /// This area is all that is left after a crop action.
    ///
    /// This area has had edits applied to it.
    ///
    /// The area where an ingredient was placed/added.
    ///
    /// Something in this area was redacted.
    ///
    /// Area specific to a subject (human or not).
    ///
    /// A range of information was removed/deleted.
    ///
    /// Styling was applied to this area.
    ///
    /// Invisible watermarking was applied to this area for the purpose of soft binding.
    /// </summary>
    public enum RoleEnum { C2PaAreaOfInterest, C2PaCropped, C2PaDeleted, C2PaEdited, C2PaPlaced, C2PaRedacted, C2PaStyled, C2PaSubjectArea, C2PaWatermarked };

    /// <summary>
    /// Set to `ParentOf` if this is the parent ingredient.
    ///
    /// There can only be one parent ingredient in the ingredients.
    ///
    /// The relationship of the ingredient to the current asset.
    ///
    /// The current asset is derived from this ingredient.
    ///
    /// The current asset is a part of this ingredient.
    ///
    /// The ingredient was used as an input to a computational process to create or modify the
    /// asset.
    /// </summary>
    public enum Relationship { ComponentOf, InputTo, ParentOf };

    public partial struct Alg
    {
        public long[]? IntegerArray;
        public string? String;

        public static implicit operator Alg(long[] IntegerArray) => new Alg { IntegerArray = IntegerArray };
        public static implicit operator Alg(string String) => new Alg { String = String };
        public bool IsNull => IntegerArray == null && String == null;
    }

    public partial class ManifestDefinition
    {
        public static ManifestDefinition FromJson(string json) => JsonSerializer.Deserialize<ManifestDefinition>(json, ContentAuthenticity.Schema.Builder.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ManifestDefinition self) => JsonSerializer.Serialize(self, ContentAuthenticity.Schema.Builder.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                KindEnumConverter.Singleton,
                AlgConverter.Singleton,
                ShapeTypeConverter.Singleton,
                UnitConverter.Singleton,
                TimeTypeConverter.Singleton,
                RegionTypeConverter.Singleton,
                RoleEnumConverter.Singleton,
                RelationshipConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class KindEnumConverter : JsonConverter<KindEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(KindEnum);

        public override KindEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Binary":
                    return KindEnum.Binary;
                case "Cbor":
                    return KindEnum.Cbor;
                case "Json":
                    return KindEnum.Json;
                case "Uri":
                    return KindEnum.Uri;
            }
            throw new Exception("Cannot unmarshal type KindEnum");
        }

        public override void Write(Utf8JsonWriter writer, KindEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case KindEnum.Binary:
                    JsonSerializer.Serialize(writer, "Binary", options);
                    return;
                case KindEnum.Cbor:
                    JsonSerializer.Serialize(writer, "Cbor", options);
                    return;
                case KindEnum.Json:
                    JsonSerializer.Serialize(writer, "Json", options);
                    return;
                case KindEnum.Uri:
                    JsonSerializer.Serialize(writer, "Uri", options);
                    return;
            }
            throw new Exception("Cannot marshal type KindEnum");
        }

        public static readonly KindEnumConverter Singleton = new KindEnumConverter();
    }

    internal class AlgConverter : JsonConverter<Alg>
    {
        public override bool CanConvert(Type t) => t == typeof(Alg);

        public override Alg Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.Null:
                    return new Alg { };
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    return new Alg { String = stringValue };
                case JsonTokenType.StartArray:
                    var arrayValue = JsonSerializer.Deserialize<long[]>(ref reader, options);
                    return new Alg { IntegerArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type Alg");
        }

        public override void Write(Utf8JsonWriter writer, Alg value, JsonSerializerOptions options)
        {
            if (value.IsNull)
            {
                writer.WriteNullValue();
                return;
            }
            if (value.String != null)
            {
                JsonSerializer.Serialize(writer, value.String, options);
                return;
            }
            if (value.IntegerArray != null)
            {
                JsonSerializer.Serialize(writer, value.IntegerArray, options);
                return;
            }
            throw new Exception("Cannot marshal type Alg");
        }

        public static readonly AlgConverter Singleton = new AlgConverter();
    }

    internal class ShapeTypeConverter : JsonConverter<ShapeType>
    {
        public override bool CanConvert(Type t) => t == typeof(ShapeType);

        public override ShapeType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "circle":
                    return ShapeType.Circle;
                case "polygon":
                    return ShapeType.Polygon;
                case "rectangle":
                    return ShapeType.Rectangle;
            }
            throw new Exception("Cannot unmarshal type ShapeType");
        }

        public override void Write(Utf8JsonWriter writer, ShapeType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ShapeType.Circle:
                    JsonSerializer.Serialize(writer, "circle", options);
                    return;
                case ShapeType.Polygon:
                    JsonSerializer.Serialize(writer, "polygon", options);
                    return;
                case ShapeType.Rectangle:
                    JsonSerializer.Serialize(writer, "rectangle", options);
                    return;
            }
            throw new Exception("Cannot marshal type ShapeType");
        }

        public static readonly ShapeTypeConverter Singleton = new ShapeTypeConverter();
    }

    internal class UnitConverter : JsonConverter<Unit>
    {
        public override bool CanConvert(Type t) => t == typeof(Unit);

        public override Unit Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "percent":
                    return Unit.Percent;
                case "pixel":
                    return Unit.Pixel;
            }
            throw new Exception("Cannot unmarshal type Unit");
        }

        public override void Write(Utf8JsonWriter writer, Unit value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Unit.Percent:
                    JsonSerializer.Serialize(writer, "percent", options);
                    return;
                case Unit.Pixel:
                    JsonSerializer.Serialize(writer, "pixel", options);
                    return;
            }
            throw new Exception("Cannot marshal type Unit");
        }

        public static readonly UnitConverter Singleton = new UnitConverter();
    }

    internal class TimeTypeConverter : JsonConverter<TimeType>
    {
        public override bool CanConvert(Type t) => t == typeof(TimeType);

        public override TimeType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "npt")
            {
                return TimeType.Npt;
            }
            throw new Exception("Cannot unmarshal type TimeType");
        }

        public override void Write(Utf8JsonWriter writer, TimeType value, JsonSerializerOptions options)
        {
            if (value == TimeType.Npt)
            {
                JsonSerializer.Serialize(writer, "npt", options);
                return;
            }
            throw new Exception("Cannot marshal type TimeType");
        }

        public static readonly TimeTypeConverter Singleton = new TimeTypeConverter();
    }

    internal class RegionTypeConverter : JsonConverter<RegionType>
    {
        public override bool CanConvert(Type t) => t == typeof(RegionType);

        public override RegionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "frame":
                    return RegionType.Frame;
                case "identified":
                    return RegionType.Identified;
                case "spatial":
                    return RegionType.Spatial;
                case "temporal":
                    return RegionType.Temporal;
                case "textual":
                    return RegionType.Textual;
            }
            throw new Exception("Cannot unmarshal type RegionType");
        }

        public override void Write(Utf8JsonWriter writer, RegionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case RegionType.Frame:
                    JsonSerializer.Serialize(writer, "frame", options);
                    return;
                case RegionType.Identified:
                    JsonSerializer.Serialize(writer, "identified", options);
                    return;
                case RegionType.Spatial:
                    JsonSerializer.Serialize(writer, "spatial", options);
                    return;
                case RegionType.Temporal:
                    JsonSerializer.Serialize(writer, "temporal", options);
                    return;
                case RegionType.Textual:
                    JsonSerializer.Serialize(writer, "textual", options);
                    return;
            }
            throw new Exception("Cannot marshal type RegionType");
        }

        public static readonly RegionTypeConverter Singleton = new RegionTypeConverter();
    }

    internal class RoleEnumConverter : JsonConverter<RoleEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(RoleEnum);

        public override RoleEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "c2pa.areaOfInterest":
                    return RoleEnum.C2PaAreaOfInterest;
                case "c2pa.cropped":
                    return RoleEnum.C2PaCropped;
                case "c2pa.deleted":
                    return RoleEnum.C2PaDeleted;
                case "c2pa.edited":
                    return RoleEnum.C2PaEdited;
                case "c2pa.placed":
                    return RoleEnum.C2PaPlaced;
                case "c2pa.redacted":
                    return RoleEnum.C2PaRedacted;
                case "c2pa.styled":
                    return RoleEnum.C2PaStyled;
                case "c2pa.subjectArea":
                    return RoleEnum.C2PaSubjectArea;
                case "c2pa.watermarked":
                    return RoleEnum.C2PaWatermarked;
            }
            throw new Exception("Cannot unmarshal type RoleEnum");
        }

        public override void Write(Utf8JsonWriter writer, RoleEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case RoleEnum.C2PaAreaOfInterest:
                    JsonSerializer.Serialize(writer, "c2pa.areaOfInterest", options);
                    return;
                case RoleEnum.C2PaCropped:
                    JsonSerializer.Serialize(writer, "c2pa.cropped", options);
                    return;
                case RoleEnum.C2PaDeleted:
                    JsonSerializer.Serialize(writer, "c2pa.deleted", options);
                    return;
                case RoleEnum.C2PaEdited:
                    JsonSerializer.Serialize(writer, "c2pa.edited", options);
                    return;
                case RoleEnum.C2PaPlaced:
                    JsonSerializer.Serialize(writer, "c2pa.placed", options);
                    return;
                case RoleEnum.C2PaRedacted:
                    JsonSerializer.Serialize(writer, "c2pa.redacted", options);
                    return;
                case RoleEnum.C2PaStyled:
                    JsonSerializer.Serialize(writer, "c2pa.styled", options);
                    return;
                case RoleEnum.C2PaSubjectArea:
                    JsonSerializer.Serialize(writer, "c2pa.subjectArea", options);
                    return;
                case RoleEnum.C2PaWatermarked:
                    JsonSerializer.Serialize(writer, "c2pa.watermarked", options);
                    return;
            }
            throw new Exception("Cannot marshal type RoleEnum");
        }

        public static readonly RoleEnumConverter Singleton = new RoleEnumConverter();
    }

    internal class RelationshipConverter : JsonConverter<Relationship>
    {
        public override bool CanConvert(Type t) => t == typeof(Relationship);

        public override Relationship Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "componentOf":
                    return Relationship.ComponentOf;
                case "inputTo":
                    return Relationship.InputTo;
                case "parentOf":
                    return Relationship.ParentOf;
            }
            throw new Exception("Cannot unmarshal type Relationship");
        }

        public override void Write(Utf8JsonWriter writer, Relationship value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Relationship.ComponentOf:
                    JsonSerializer.Serialize(writer, "componentOf", options);
                    return;
                case Relationship.InputTo:
                    JsonSerializer.Serialize(writer, "inputTo", options);
                    return;
                case Relationship.ParentOf:
                    JsonSerializer.Serialize(writer, "parentOf", options);
                    return;
            }
            throw new Exception("Cannot marshal type Relationship");
        }

        public static readonly RelationshipConverter Singleton = new RelationshipConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
