// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using ContentAuthenticity.Schema.Settings;
//
//    var settings = Settings.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace ContentAuthenticity.Schema.Settings
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Settings for configuring all aspects of c2pa-rs.
    ///
    /// [`Settings::default`] is used as the thread-local configuration by default.
    /// Use [`Settings::new`] together with builder-style methods such as
    /// [`with_toml`] to construct a configuration without modifying thread-local
    /// state.
    ///
    /// [`with_toml`]: Settings::with_toml
    /// </summary>
    public partial class Settings
    {
        /// <summary>
        /// Settings for configuring the [`Builder`].
        ///
        /// [`Builder`]: crate::Builder
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("builder")]
        public Builder? Builder { get; set; }

        /// <summary>
        /// Settings for configuring the CAWG trust lists.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("cawg_trust")]
        public CawgTrust? CawgTrust { get; set; }

        /// <summary>
        /// Settings for configuring the CAWG x509 signer, accessible via [`Settings::signer`].
        /// </summary>
        [JsonPropertyName("cawg_x509_signer")]
        public CawgX509SignerClass? CawgX509Signer { get; set; }

        /// <summary>
        /// Settings for configuring core features.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("core")]
        public Core? Core { get; set; }

        /// <summary>
        /// Settings for configuring the base C2PA signer, accessible via [`Settings::signer`].
        /// </summary>
        [JsonPropertyName("signer")]
        public CawgX509SignerClass? Signer { get; set; }

        /// <summary>
        /// Settings for configuring the C2PA trust lists.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("trust")]
        public CawgTrust? Trust { get; set; }

        /// <summary>
        /// Settings for configuring verification.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify")]
        public Verify? Verify { get; set; }

        /// <summary>
        /// Version of the configuration.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public long? Version { get; set; }
    }

    /// <summary>
    /// Settings for configuring the [`Builder`].
    ///
    /// [`Builder`]: crate::Builder
    ///
    /// Settings for the [Builder][crate::Builder].
    /// </summary>
    public partial class Builder
    {
        /// <summary>
        /// Settings for configuring fields in an [Actions][crate::assertions::Actions] assertion.
        ///
        /// For more information on the reasoning behind this field see [ActionsSettings].
        /// </summary>
        [JsonPropertyName("actions")]
        public Actions Actions { get; set; }

        /// <summary>
        /// Settings for configuring auto-generation of the [`TimeStamp`] assertion.
        ///
        /// [`TimeStamp`]: crate::assertions::TimeStamp
        /// </summary>
        [JsonPropertyName("auto_timestamp_assertion")]
        public AutoTimestampAssertion AutoTimestampAssertion { get; set; }

        /// <summary>
        /// Whether to create [`CertificateStatus`] assertions for manifests to store certificate
        /// revocation
        /// status. The assertion can be fetched for the active manifest or for all manifests
        /// (including
        /// ingredients).
        ///
        /// The default is to not fetch them at all.
        ///
        /// For more information, see [Certificate status assertion - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#certificate_status_assertion).
        ///
        /// [`CertificateStatus`]: crate::assertions::CertificateStatus
        /// </summary>
        [JsonPropertyName("certificate_status_fetch")]
        public CertificateStatusFetchEnum? CertificateStatusFetch { get; set; }

        /// <summary>
        /// Whether to only use [`CertificateStatus`] assertions to check certificate revocation
        /// status. If there
        /// is a stapled OCSP in the COSE claim of the manifest, it will be ignored. If
        /// [`Verify::ocsp_fetch`] is
        /// enabled, it will also be ignored.
        ///
        /// The default value is false.
        ///
        /// [`CertificateStatus`]: crate::assertions::CertificateStatus
        /// [`Verify::ocsp_fetch`]: crate::settings::Verify::ocsp_fetch
        /// </summary>
        [JsonPropertyName("certificate_status_should_override")]
        public bool? CertificateStatusShouldOverride { get; set; }

        /// <summary>
        /// When set, used as [`ClaimGeneratorInfo`] when
        /// [`ManifestDefinition::claim_generator_info`](crate::builder::ManifestDefinition) is empty
        /// (e.g. key omitted in JSON or an empty array). If `None` or when the definition lists at
        /// least one generator, that path does not use this value.
        /// </summary>
        [JsonPropertyName("claim_generator_info")]
        public ClaimGeneratorInfoClass? ClaimGeneratorInfo { get; set; }

        /// <summary>
        /// Assertions with a base label included in this list will be automatically marked as a
        /// created assertion.
        /// Assertions not in this list will be automatically marked as gathered.
        ///
        /// Note that the label should be a **base label**, not including the assertion version nor
        /// instance.
        ///
        /// See more information on the difference between created vs gathered assertions in the spec
        /// here:
        /// [fields - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_fields)
        /// </summary>
        [JsonPropertyName("created_assertion_labels")]
        public string[]? CreatedAssertionLabels { get; set; }

        /// <summary>
        /// Whether to generate a C2PA archive (instead of zip) when writing the manifest builder.
        /// Now always defaults to true - the ability to disable it will be removed in the future.
        /// </summary>
        [JsonPropertyName("generate_c2pa_archive")]
        public bool? GenerateC2PaArchive { get; set; }

        /// <summary>
        /// The default [`BuilderIntent`] for the [`Builder`].
        ///
        /// See [`BuilderIntent`] for more information.
        ///
        /// [`BuilderIntent`]: crate::BuilderIntent
        /// [`Builder`]: crate::Builder
        /// </summary>
        [JsonPropertyName("intent")]
        public Intent? Intent { get; set; }

        /// <summary>
        /// When `true`, use [`BoxHash`] instead of [`crate::assertions::DataHash`] for formats
        /// that support it (JPEG, PNG, GIF, etc.) when no explicit hard binding assertion has
        /// been set.
        ///
        /// Formats that support `BoxHash` can embed the C2PA manifest as a new chunk/segment
        /// without shifting existing byte offsets, so a placeholder is never required.
        /// Setting this to `true` enables the direct workflow (`Builder::sign_embeddable`
        /// Mode 2) for those formats and makes `Builder::needs_placeholder` return `false`.
        ///
        /// Defaults to `false` to preserve existing behaviour until `BoxHash` support is
        /// more widely tested.  Set to `true` (or configure it per-[`Context`]) whenever
        /// you are ready to prefer box-based hashing for supported formats.
        ///
        /// [`BoxHash`]: crate::assertions::BoxHash
        /// [`Context`]: crate::Context
        /// </summary>
        [JsonPropertyName("prefer_box_hash")]
        public bool PreferBoxHash { get; set; }

        /// <summary>
        /// Various settings for configuring automatic thumbnail generation.
        /// </summary>
        [JsonPropertyName("thumbnail")]
        public Thumbnail Thumbnail { get; set; }

        /// <summary>
        /// The name of the vendor creating the content credential.
        /// </summary>
        [JsonPropertyName("vendor")]
        public string? Vendor { get; set; }
    }

    /// <summary>
    /// Settings for configuring fields in an [Actions][crate::assertions::Actions] assertion.
    ///
    /// For more information on the reasoning behind this field see [ActionsSettings].
    ///
    /// Settings for configuring the "base" [Actions][crate::assertions::Actions] assertion.
    ///
    /// The reason this setting exists only for an [Actions][crate::assertions::Actions]
    /// assertion
    /// is because of its mandations and reusable fields.
    /// </summary>
    public partial class Actions
    {
        /// <summary>
        /// Whether or not to set the
        /// [Actions::all_actions_included][crate::assertions::Actions::all_actions_included]
        /// field.
        /// </summary>
        [JsonPropertyName("all_actions_included")]
        public bool? AllActionsIncluded { get; set; }

        /// <summary>
        /// Whether to automatically generate a c2pa.created [Action] assertion or error that it
        /// doesn't already exist.
        ///
        /// For more information about the mandatory conditions for a c2pa.created action assertion,
        /// see the
        /// [C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_mandatory_presence_of_at_least_one_actions_assertion).
        /// </summary>
        [JsonPropertyName("auto_created_action")]
        public AutoCreatedAction AutoCreatedAction { get; set; }

        /// <summary>
        /// Whether to automatically generate a c2pa.opened [Action] assertion or error that it
        /// doesn't already exist.
        ///
        /// For more information about the mandatory conditions for a c2pa.opened action assertion,
        /// see the
        /// [C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_mandatory_presence_of_at_least_one_actions_assertion).
        /// </summary>
        [JsonPropertyName("auto_opened_action")]
        public AutoCreatedAction AutoOpenedAction { get; set; }

        /// <summary>
        /// Whether to automatically generate a c2pa.placed [Action] assertion or error that it
        /// doesn't already exist.
        ///
        /// For more information about the mandatory conditions for a c2pa.placed action assertion,
        /// see
        /// [Relationship - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_relationship)
        /// </summary>
        [JsonPropertyName("auto_placed_action")]
        public AutoCreatedAction AutoPlacedAction { get; set; }

        /// <summary>
        /// Templates to be added to the [Actions::templates][crate::assertions::Actions::templates]
        /// field.
        /// </summary>
        [JsonPropertyName("templates")]
        public TemplateElement[]? Templates { get; set; }
    }

    /// <summary>
    /// Whether to automatically generate a c2pa.created [Action] assertion or error that it
    /// doesn't already exist.
    ///
    /// For more information about the mandatory conditions for a c2pa.created action assertion,
    /// see the
    /// [C2PA Technical
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_mandatory_presence_of_at_least_one_actions_assertion).
    ///
    /// Settings for the auto actions (e.g. created, opened, placed).
    ///
    /// Whether to automatically generate a c2pa.opened [Action] assertion or error that it
    /// doesn't already exist.
    ///
    /// For more information about the mandatory conditions for a c2pa.opened action assertion,
    /// see the
    /// [C2PA Technical
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_mandatory_presence_of_at_least_one_actions_assertion).
    ///
    /// Whether to automatically generate a c2pa.placed [Action] assertion or error that it
    /// doesn't already exist.
    ///
    /// For more information about the mandatory conditions for a c2pa.placed action assertion,
    /// see
    /// [Relationship - C2PA Technical
    /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_relationship)
    /// </summary>
    public partial class AutoCreatedAction
    {
        /// <summary>
        /// Whether to enable this auto action or not.
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// The default source type for the auto action.
        /// </summary>
        [JsonPropertyName("source_type")]
        public string? SourceType { get; set; }
    }

    /// <summary>
    /// Settings for an action template.
    /// </summary>
    public partial class TemplateElement
    {
        /// <summary>
        /// The label associated with this action. See
        /// ([c2pa_action][crate::assertions::actions::c2pa_action]).
        /// </summary>
        [JsonPropertyName("action")]
        public string Action { get; set; }

        /// <summary>
        /// Description of the template.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Reference to an icon.
        /// </summary>
        [JsonPropertyName("icon")]
        public IconClass? Icon { get; set; }

        /// <summary>
        /// The software agent that performed the action.
        /// </summary>
        [JsonPropertyName("software_agent")]
        public ClaimGeneratorInfoClass? SoftwareAgent { get; set; }

        /// <summary>
        /// 0-based index into the softwareAgents array
        /// </summary>
        [JsonPropertyName("software_agent_index")]
        public long? SoftwareAgentIndex { get; set; }

        /// <summary>
        /// One of the defined URI values at `&lt;https://cv.iptc.org/newscodes/digitalsourcetype/&gt;`
        /// </summary>
        [JsonPropertyName("source_type")]
        public string? SourceType { get; set; }

        /// <summary>
        /// Additional parameters for the template
        /// </summary>
        [JsonPropertyName("template_parameters")]
        public Dictionary<string, object>? TemplateParameters { get; set; }
    }

    /// <summary>
    /// A reference to a resource to be used in JSON serialization.
    ///
    /// The underlying data can be read as a stream via
    /// [`Reader::resource_to_stream`][crate::Reader::resource_to_stream].
    /// </summary>
    public partial class IconClass
    {
        /// <summary>
        /// The algorithm used to hash the resource (if applicable).
        /// </summary>
        [JsonPropertyName("alg")]
        public string? Alg { get; set; }

        /// <summary>
        /// More detailed data types as defined in the C2PA spec.
        /// </summary>
        [JsonPropertyName("data_types")]
        public DataTypeElement[]? DataTypes { get; set; }

        /// <summary>
        /// The mime type of the referenced resource.
        /// </summary>
        [JsonPropertyName("format")]
        public string Format { get; set; }

        /// <summary>
        /// The hash of the resource (if applicable).
        /// </summary>
        [JsonPropertyName("hash")]
        public string? Hash { get; set; }

        /// <summary>
        /// A URI that identifies the resource as referenced from the manifest.
        ///
        /// This may be a JUMBF URI, a file path, a URL or any other string.
        /// Relative JUMBF URIs will be resolved with the manifest label.
        /// Relative file paths will be resolved with the base path if provided.
        /// </summary>
        [JsonPropertyName("identifier")]
        public string Identifier { get; set; }
    }

    public partial class DataTypeElement
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("version")]
        public string? Version { get; set; }
    }

    /// <summary>
    /// Settings for the claim generator info.
    /// </summary>
    public partial class ClaimGeneratorInfoClass
    {
        /// <summary>
        /// Reference to an icon.
        /// </summary>
        [JsonPropertyName("icon")]
        public IconClass? Icon { get; set; }

        /// <summary>
        /// A human readable string naming the claim_generator.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Settings for the claim generator info's operating system field.
        /// </summary>
        [JsonPropertyName("operating_system")]
        public string? OperatingSystem { get; set; }

        /// <summary>
        /// A human readable string of the product's version.
        /// </summary>
        [JsonPropertyName("version")]
        public string? Version { get; set; }
    }

    /// <summary>
    /// Settings for configuring auto-generation of the [`TimeStamp`] assertion.
    ///
    /// [`TimeStamp`]: crate::assertions::TimeStamp
    ///
    /// Settings for configuring auto-generation of the [`TimeStamp`] assertion.
    ///
    /// Useful when a manifest was signed offline and you want to attach a trusted timestamp to
    /// it later.
    ///
    /// [`TimeStamp`]: crate::assertions::TimeStamp
    /// </summary>
    public partial class AutoTimestampAssertion
    {
        /// <summary>
        /// Whether to auto-generate a [`TimeStamp`] assertion for the
        /// [`TimeStampSettings::fetch_scope`].
        ///
        /// Note that for this setting to take effect, a timestamping authority URL must be set in
        /// the
        /// [`Signer::time_authority_url`]. If the signer is acquired from settings via
        /// [`Settings::signer`],
        /// the URL can be set in [`SignerSettings`].
        ///
        /// The default value is false.
        ///
        /// [`TimeStamp`]: crate::assertions::TimeStamp
        /// [`Signer::time_authority_url`]: crate::Signer::time_authority_url
        /// [`Settings::signer`]: crate::settings::signer
        /// [`SignerSettings`]: crate::settings::signer::SignerSettings
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Which manifests to fetch timestamps for.
        ///
        /// The default value is [`TimeStampFetchScope::All`].
        /// </summary>
        [JsonPropertyName("fetch_scope")]
        public FetchScope FetchScope { get; set; }

        /// <summary>
        /// Whether to skip fetching timestamps for manifests that already have one.
        ///
        /// This setting will account for both existing [`TimeStamp`] assertions and timestamps
        /// embedded
        /// in the claim.
        ///
        /// The default value is true.
        ///
        /// [`TimeStamp`]: crate::assertions::TimeStamp
        /// </summary>
        [JsonPropertyName("skip_existing")]
        public bool SkipExisting { get; set; }
    }

    /// <summary>
    /// This is a new digital creation, a DigitalSourceType is required.
    ///
    /// The Manifest must not have have a parent ingredient.
    /// A `c2pa.created` action will be added if not provided.
    /// </summary>
    public partial class IntentClass
    {
        [JsonPropertyName("create")]
        public string Create { get; set; }
    }

    /// <summary>
    /// Various settings for configuring automatic thumbnail generation.
    ///
    /// Settings for controlling automatic thumbnail generation.
    /// </summary>
    public partial class Thumbnail
    {
        /// <summary>
        /// Whether or not to automatically generate thumbnails.
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// This setting is only applicable if the crate is compiled with the `add_thumbnails`
        /// feature.
        /// &lt;/div&gt;
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Format of the thumbnail.
        ///
        /// If this field isn't specified, the thumbnail format will correspond to the
        /// input format.
        ///
        /// The default value is None.
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get; set; }

        /// <summary>
        /// Whether to ignore thumbnail generation errors.
        ///
        /// This may occur, for instance, if the thumbnail media type or color layout isn't
        /// supported.
        ///
        /// The default value is true.
        /// </summary>
        [JsonPropertyName("ignore_errors")]
        public bool IgnoreErrors { get; set; }

        /// <summary>
        /// The size of the longest edge of the thumbnail.
        ///
        /// This function will resize the input to preserve aspect ratio.
        ///
        /// The default value is 1024.
        /// </summary>
        [JsonPropertyName("long_edge")]
        public long LongEdge { get; set; }

        /// <summary>
        /// Whether or not to prefer a smaller sized media format for the thumbnail.
        ///
        /// Note that [ThumbnailSettings::format] takes precedence over this field. In addition,
        /// if the output format is unsupported, it will default to the smallest format regardless
        /// of the value of this field.
        ///
        /// For instance, if the source input type is a PNG, but it doesn't have an alpha channel,
        /// the image will be converted to a JPEG of smaller size.
        ///
        /// The default value is true.
        /// </summary>
        [JsonPropertyName("prefer_smallest_format")]
        public bool PreferSmallestFormat { get; set; }

        /// <summary>
        /// The output quality of the thumbnail.
        ///
        /// This setting contains sensible defaults for things like quality, compression, and
        /// algorithms for various formats.
        ///
        /// The default value is [`ThumbnailQuality::Medium`].
        /// </summary>
        [JsonPropertyName("quality")]
        public Quality Quality { get; set; }
    }

    /// <summary>
    /// Settings for configuring the CAWG trust lists.
    ///
    /// Settings to configure the trust list.
    ///
    /// Settings for configuring the C2PA trust lists.
    /// </summary>
    public partial class CawgTrust
    {
        /// <summary>
        /// List of explicitly allowed certificates as a PEM bundle.
        /// </summary>
        [JsonPropertyName("allowed_list")]
        public string? AllowedList { get; set; }

        /// <summary>
        /// List of default trust anchor root certificates as a PEM bundle.
        ///
        /// Normally this option contains the official C2PA-recognized trust anchors found here:
        /// &lt;https://github.com/c2pa-org/conformance-public/tree/main/trust-list&gt;
        /// </summary>
        [JsonPropertyName("trust_anchors")]
        public string? TrustAnchors { get; set; }

        /// <summary>
        /// List of allowed extended key usage (EKU) object identifiers (OID) that
        /// certificates must have.
        /// </summary>
        [JsonPropertyName("trust_config")]
        public string? TrustConfig { get; set; }

        /// <summary>
        /// List of additional user-provided trust anchor root certificates as a PEM bundle.
        /// </summary>
        [JsonPropertyName("user_anchors")]
        public string? UserAnchors { get; set; }

        /// <summary>
        /// Whether to verify certificates against the trust lists specified in [`Trust`]. This
        /// option is ONLY applicable to CAWG.
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// Verifying trust is REQUIRED by the CAWG spec. This option should only be used for
        /// development or testing.
        /// &lt;/div&gt;
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_trust_list")]
        public bool? VerifyTrustList { get; set; }
    }

    /// <summary>
    /// A signer configured locally.
    ///
    /// A signer configured remotely.
    /// </summary>
    public partial class CawgX509SignerClass
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("local")]
        public Local? Local { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("remote")]
        public Remote? Remote { get; set; }
    }

    public partial class Local
    {
        /// <summary>
        /// Algorithm to use for signing.
        /// </summary>
        [JsonPropertyName("alg")]
        public Alg Alg { get; set; }

        /// <summary>
        /// Private key used for signing (PEM format).
        /// </summary>
        [JsonPropertyName("private_key")]
        public string PrivateKey { get; set; }

        /// <summary>
        /// Referenced assertions for CAWG identity signing (optional).
        /// </summary>
        [JsonPropertyName("referenced_assertions")]
        public string[]? ReferencedAssertions { get; set; }

        /// <summary>
        /// Roles for CAWG identity signing (optional).
        /// </summary>
        [JsonPropertyName("roles")]
        public string[]? Roles { get; set; }

        /// <summary>
        /// Certificate used for signing (PEM format).
        /// </summary>
        [JsonPropertyName("sign_cert")]
        public string SignCert { get; set; }

        /// <summary>
        /// Time stamp authority URL for signing.
        /// </summary>
        [JsonPropertyName("tsa_url")]
        public string? TsaUrl { get; set; }
    }

    public partial class Remote
    {
        /// <summary>
        /// Algorithm to use for signing.
        /// </summary>
        [JsonPropertyName("alg")]
        public Alg Alg { get; set; }

        /// <summary>
        /// Referenced assertions for CAWG identity signing (optional).
        /// </summary>
        [JsonPropertyName("referenced_assertions")]
        public string[]? ReferencedAssertions { get; set; }

        /// <summary>
        /// Roles for CAWG identity signing (optional).
        /// </summary>
        [JsonPropertyName("roles")]
        public string[]? Roles { get; set; }

        /// <summary>
        /// Certificate used for signing (PEM format).
        /// </summary>
        [JsonPropertyName("sign_cert")]
        public string SignCert { get; set; }

        /// <summary>
        /// Time stamp authority URL for signing.
        /// </summary>
        [JsonPropertyName("tsa_url")]
        public string? TsaUrl { get; set; }

        /// <summary>
        /// URL that the signer will use for signing.
        /// A POST request with a byte-stream will be sent to this URL.
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }
    }

    /// <summary>
    /// Settings for configuring core features.
    ///
    /// Settings to configure core features.
    /// </summary>
    public partial class Core
    {
        /// <summary>
        /// &lt;div class="warning"&gt;
        /// The CAWG identity assertion does not currently respect this setting.
        /// See [Issue #1645](https://github.com/contentauth/c2pa-rs/issues/1645).
        /// &lt;/div&gt;
        ///
        /// List of host patterns that are allowed for network requests.
        ///
        /// Each pattern may include:
        /// - A scheme (e.g. `https://` or `http://`)
        /// - A hostname or IP address (e.g. `contentauthenticity.org` or `192.0.2.1`)
        /// - The hostname may contain a single leading wildcard (e.g. `*.contentauthenticity.org`)
        /// - An optional port (e.g. `contentauthenticity.org:443` or `192.0.2.1:8080`)
        ///
        /// Matching is case-insensitive. A wildcard pattern such as `*.contentauthenticity.org`
        /// matches
        /// `sub.contentauthenticity.org`, but does not match `contentauthenticity.org` or
        /// `fakecontentauthenticity.org`.
        /// If a scheme is present in the pattern, only URIs using the same scheme are considered a
        /// match. If the scheme
        /// is omitted, any scheme is allowed as long as the host matches.
        ///
        /// The behavior is as follows:
        /// - `None` (default) no filtering enabled.
        /// - `Some(vec)` where `vec` is empty, all traffic is blocked.
        /// - `Some(vec)` with at least one pattern, filtering enabled for only those patterns.
        ///
        /// # Examples
        ///
        /// Pattern: `*.contentauthenticity.org`
        /// - Does match:
        /// - `https://sub.contentauthenticity.org`
        /// - `http://api.contentauthenticity.org`
        /// - Does **not** match:
        /// - `https://contentauthenticity.org` (no subdomain)
        /// - `https://sub.fakecontentauthenticity.org` (different host)
        ///
        /// Pattern: `http://192.0.2.1:8080`
        /// - Does match:
        /// - `http://192.0.2.1:8080`
        /// - Does **not** match:
        /// - `https://192.0.2.1:8080` (scheme mismatch)
        /// - `http://192.0.2.1` (port omitted)
        /// - `http://192.0.2.2:8080` (different IP address)
        ///
        /// These settings are applied by the SDK's HTTP resolvers to restrict network requests.
        /// When network requests occur depends on the operations being performed (reading manifests,
        /// validating credentials, timestamping, etc.).
        /// </summary>
        [JsonPropertyName("allowed_network_hosts")]
        public string[]? AllowedNetworkHosts { get; set; }

        /// <summary>
        /// Maximum amount of data in megabytes that will be loaded into memory before
        /// being stored in temporary files on the disk.
        ///
        /// This option defaults to 512MB and can result in noticeable performance improvements.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("backing_store_memory_threshold_in_mb")]
        public long? BackingStoreMemoryThresholdInMb { get; set; }

        /// <summary>
        /// Whether to decode CAWG [`IdentityAssertion`]s during reading in the [`Reader`].
        ///
        /// This option defaults to true.
        ///
        /// [`IdentityAssertion`]: crate::identity::IdentityAssertion
        /// [`Reader`]: crate::Reader
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("decode_identity_assertions")]
        public bool? DecodeIdentityAssertions { get; set; }

        /// <summary>
        /// Maximum size in megabytes of a Brotli-decompressed JUMBF manifest.
        /// Limits memory consumption from decompression bomb attacks.
        ///
        /// The default is 32 MB.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("max_decompressed_manifest_size_in_mb")]
        public long? MaxDecompressedManifestSizeInMb { get; set; }

        /// <summary>
        /// Size of the [`BmffHash`] merkle tree chunks in kilobytes.
        ///
        /// This option is associated with the [`MerkleMap::fixed_block_size`] field.
        ///
        /// See more information in the spec here:
        /// [bmff_based_hash - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_bmff_based_hash)
        ///
        /// [`MerkleMap::fixed_block_size`]: crate::assertions::MerkleMap::fixed_block_size
        /// [`BmffHash`]: crate::assertions::BmffHash
        /// </summary>
        [JsonPropertyName("merkle_tree_chunk_size_in_kb")]
        public long? MerkleTreeChunkSizeInKb { get; set; }

        /// <summary>
        /// Maximum number of proof hashes stored in UUID merkle boxes when  generating a
        /// [`BmffHash`] merkle tree.  This
        /// determines the Merkle tree row stored in the manifest and thus the number of proof hashes
        /// that need to be
        /// provided during validation. The value may be 0 to store just leaf node hashes (no UUID
        /// boxes are generated in this case).
        ///
        /// This option defaults to 5.
        ///
        /// See more information in the spec here:
        /// [bmff_based_hash - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_bmff_based_hash)
        ///
        /// [`BmffHash`]: crate::assertions::BmffHash
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("merkle_tree_max_proofs")]
        public long? MerkleTreeMaxProofs { get; set; }

        /// <summary>
        /// Whether to prefer compressing manifests. This can reduce the size of the manifest.
        /// Compressed manifest
        /// are not always possible and will default back to uncompressed if the manifest contains
        /// features
        /// that are not compatible with compression.
        ///
        /// The default value is false.
        ///
        /// See more information in the spec here:
        /// [Compressed manifests - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_compressed_boxes)
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("prefer_compress_manifests")]
        public bool? PreferCompressManifests { get; set; }
    }

    /// <summary>
    /// Settings for configuring verification.
    ///
    /// Settings to configure the verification process.
    /// </summary>
    public partial class Verify
    {
        /// <summary>
        /// Whether to fetch the certificates OCSP status during validation.
        ///
        /// Revocation status is checked in the following order:
        /// 1. The OCSP staple stored in the COSE claim of the manifest
        /// 2. Otherwise if `ocsp_fetch` is enabled, it fetches a new OCSP status
        /// 3. Otherwise if `ocsp_fetch` is disabled, it checks `CertificateStatus` assertions
        ///
        /// The default value is false.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ocsp_fetch")]
        public bool? OcspFetch { get; set; }

        /// <summary>
        /// Whether to fetch remote manifests in the following scenarios:
        /// - Constructing a [`Reader`]
        /// - Adding an [`Ingredient`] to the [`Builder`]
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// This setting is only applicable if the crate is compiled with the
        /// `fetch_remote_manifests` feature.
        /// &lt;/div&gt;
        ///
        /// [`Reader`]: crate::Reader
        /// [`Ingredient`]: crate::Ingredient
        /// [`Builder`]: crate::Builder
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("remote_manifest_fetch")]
        public bool? RemoteManifestFetch { get; set; }

        /// <summary>
        /// Whether to skip ingredient conflict resolution when multiple ingredients have the same
        /// manifest identifier. This settings is only applicable for C2PA v2 validation.
        ///
        /// The default value is false.
        ///
        /// See more information in the spec here:
        /// [versioning_manifests_due_to_conflicts - C2PA Technical
        /// Specification](https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_versioning_manifests_due_to_conflicts)
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("skip_ingredient_conflict_resolution")]
        public bool? SkipIngredientConflictResolution { get; set; }

        /// <summary>
        /// Whether to do strictly C2PA v1 validation or otherwise the latest validation.
        ///
        /// The default value is false.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("strict_v1_validation")]
        public bool? StrictV1Validation { get; set; }

        /// <summary>
        /// Whether to verify the manifest after reading in the [`Reader`].
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// Disabling validation can improve reading performance, BUT it carries the risk of reading
        /// an invalid
        /// manifest.
        /// &lt;/div&gt;
        ///
        /// [`Reader`]: crate::Reader
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_after_reading")]
        public bool? VerifyAfterReading { get; set; }

        /// <summary>
        /// Whether to verify the manifest after signing in the [`Builder`].
        ///
        /// The default value is false.
        ///
        /// In the future, this setting will default to true.
        ///
        /// &lt;div class="warning"&gt;
        /// Disabling validation can improve signing performance, BUT it carries the risk of signing
        /// an invalid
        /// manifest.
        /// &lt;/div&gt;
        ///
        /// [`Builder`]: crate::Builder
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_after_sign")]
        public bool? VerifyAfterSign { get; set; }

        /// <summary>
        /// Whether to include asset hash validation when verifying after signing.
        ///
        /// The default value is false.
        ///
        /// Has no effect when [`Verify::verify_after_sign`] is false.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_after_sign_hash")]
        public bool? VerifyAfterSignHash { get; set; }

        /// <summary>
        /// Whether to verify the timestamp certificates against the trust lists specified in
        /// [`Trust`].
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// Verifying timestamp trust is REQUIRED by the C2PA spec. This option should only be used
        /// for development or testing.
        /// &lt;/div&gt;
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_timestamp_trust")]
        public bool? VerifyTimestampTrust { get; set; }

        /// <summary>
        /// Whether to verify certificates against the trust lists specified in [`Trust`]. To
        /// configure
        /// timestamp certificate verification, see [`Verify::verify_timestamp_trust`].
        ///
        /// The default value is true.
        ///
        /// &lt;div class="warning"&gt;
        /// Verifying trust is REQUIRED by the C2PA spec. This option should only be used for
        /// development or testing.
        /// &lt;/div&gt;
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("verify_trust")]
        public bool? VerifyTrust { get; set; }
    }

    /// <summary>
    /// Which manifests to fetch timestamps for.
    ///
    /// The default value is [`TimeStampFetchScope::All`].
    ///
    /// The scope of manifests to fetch timestamps for.
    ///
    /// See [`TimeStampSettings`] for more information.
    ///
    /// Fetch timestamps for only the parent manifest.
    ///
    /// Fetch timestmaps for all manifests in the manifest store.
    /// </summary>
    public enum FetchScope { All, Parent };

    /// <summary>
    /// Fetch OCSP for all manifests.
    ///
    /// Fetch OCSP for the active manifest only.
    /// </summary>
    public enum CertificateStatusFetchEnum { Active, All };

    /// <summary>
    /// This is an edit of a pre-existing parent asset.
    ///
    /// The Manifest must have a parent ingredient.
    /// A parent ingredient will be generated from the source stream if not otherwise provided.
    /// A `c2pa.opened action will be tied to the parent ingredient.
    ///
    /// A restricted version of Edit for non-editorial changes.
    ///
    /// There must be only one ingredient, as a parent.
    /// No changes can be made to the hashed content of the parent.
    /// There are additional restrictions on the types of changes that can be made.
    /// </summary>
    public enum IntentEnum { Edit, Update };

    /// <summary>
    /// An image in PNG format.
    ///
    /// An image in JPEG format.
    ///
    /// An image in GIF format.
    ///
    /// An image in WEBP format.
    ///
    /// An image in TIFF format.
    /// </summary>
    public enum FormatEnum { Gif, Jpeg, Png, Tiff, Webp };

    /// <summary>
    /// The output quality of the thumbnail.
    ///
    /// This setting contains sensible defaults for things like quality, compression, and
    /// algorithms for various formats.
    ///
    /// The default value is [`ThumbnailQuality::Medium`].
    ///
    /// Quality of the thumbnail.
    ///
    /// Low quality.
    ///
    /// Medium quality.
    ///
    /// High quality.
    /// </summary>
    public enum Quality { High, Low, Medium };

    /// <summary>
    /// Algorithm to use for signing.
    ///
    /// Describes the digital signature algorithms allowed by the C2PA spec.
    ///
    /// Per [§13.2, “Digital Signatures”]:
    ///
    /// &gt; All digital signatures applied as per the technical requirements of this
    /// &gt; specification shall be generated using one of the digital signature
    /// &gt; algorithms and key types listed as described in this section.
    ///
    /// [§13.2, “Digital Signatures”]:
    /// https://spec.c2pa.org/specifications/specifications/2.3/specs/C2PA_Specification.html#_digital_signatures
    ///
    /// ECDSA with SHA-256
    ///
    /// ECDSA with SHA-384
    ///
    /// ECDSA with SHA-512
    ///
    /// RSASSA-PSS using SHA-256 and MGF1 with SHA-256
    ///
    /// RSASSA-PSS using SHA-384 and MGF1 with SHA-384
    ///
    /// RSASSA-PSS using SHA-512 and MGF1 with SHA-512
    ///
    /// Edwards-Curve DSA (Ed25519 instance only)
    /// </summary>
    public enum Alg { Ed25519, Es256, Es384, Es512, Ps256, Ps384, Ps512 };

    /// <summary>
    /// The default [`BuilderIntent`] for the [`Builder`].
    ///
    /// See [`BuilderIntent`] for more information.
    ///
    /// [`BuilderIntent`]: crate::BuilderIntent
    /// [`Builder`]: crate::Builder
    /// </summary>
    public partial struct Intent
    {
        public IntentEnum? Enum;
        public IntentClass? IntentClass;

        public static implicit operator Intent(IntentEnum Enum) => new Intent { Enum = Enum };
        public static implicit operator Intent(IntentClass IntentClass) => new Intent { IntentClass = IntentClass };
        public bool IsNull => IntentClass == null && Enum == null;
    }

    public partial class Settings
    {
        public static Settings FromJson(string json) => JsonSerializer.Deserialize<Settings>(json, ContentAuthenticity.Schema.Settings.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Settings self) => JsonSerializer.Serialize(self, ContentAuthenticity.Schema.Settings.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                FetchScopeConverter.Singleton,
                CertificateStatusFetchEnumConverter.Singleton,
                IntentConverter.Singleton,
                IntentEnumConverter.Singleton,
                FormatEnumConverter.Singleton,
                QualityConverter.Singleton,
                AlgConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class FetchScopeConverter : JsonConverter<FetchScope>
    {
        public override bool CanConvert(Type t) => t == typeof(FetchScope);

        public override FetchScope Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "all":
                    return FetchScope.All;
                case "parent":
                    return FetchScope.Parent;
            }
            throw new Exception("Cannot unmarshal type FetchScope");
        }

        public override void Write(Utf8JsonWriter writer, FetchScope value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case FetchScope.All:
                    JsonSerializer.Serialize(writer, "all", options);
                    return;
                case FetchScope.Parent:
                    JsonSerializer.Serialize(writer, "parent", options);
                    return;
            }
            throw new Exception("Cannot marshal type FetchScope");
        }

        public static readonly FetchScopeConverter Singleton = new FetchScopeConverter();
    }

    internal class CertificateStatusFetchEnumConverter : JsonConverter<CertificateStatusFetchEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(CertificateStatusFetchEnum);

        public override CertificateStatusFetchEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "active":
                    return CertificateStatusFetchEnum.Active;
                case "all":
                    return CertificateStatusFetchEnum.All;
            }
            throw new Exception("Cannot unmarshal type CertificateStatusFetchEnum");
        }

        public override void Write(Utf8JsonWriter writer, CertificateStatusFetchEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case CertificateStatusFetchEnum.Active:
                    JsonSerializer.Serialize(writer, "active", options);
                    return;
                case CertificateStatusFetchEnum.All:
                    JsonSerializer.Serialize(writer, "all", options);
                    return;
            }
            throw new Exception("Cannot marshal type CertificateStatusFetchEnum");
        }

        public static readonly CertificateStatusFetchEnumConverter Singleton = new CertificateStatusFetchEnumConverter();
    }

    internal class IntentConverter : JsonConverter<Intent>
    {
        public override bool CanConvert(Type t) => t == typeof(Intent);

        public override Intent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.Null:
                    return new Intent { };
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    switch (stringValue)
                    {
                        case "edit":
                            return new Intent { Enum = IntentEnum.Edit };
                        case "update":
                            return new Intent { Enum = IntentEnum.Update };
                    }
                    break;
                case JsonTokenType.StartObject:
                    var objectValue = JsonSerializer.Deserialize<IntentClass>(ref reader, options);
                    return new Intent { IntentClass = objectValue };
            }
            throw new Exception("Cannot unmarshal type Intent");
        }

        public override void Write(Utf8JsonWriter writer, Intent value, JsonSerializerOptions options)
        {
            if (value.IsNull)
            {
                writer.WriteNullValue();
                return;
            }
            if (value.Enum != null)
            {
                switch (value.Enum)
                {
                    case IntentEnum.Edit:
                        JsonSerializer.Serialize(writer, "edit", options);
                        return;
                    case IntentEnum.Update:
                        JsonSerializer.Serialize(writer, "update", options);
                        return;
                }
            }
            if (value.IntentClass != null)
            {
                JsonSerializer.Serialize(writer, value.IntentClass, options);
                return;
            }
            throw new Exception("Cannot marshal type Intent");
        }

        public static readonly IntentConverter Singleton = new IntentConverter();
    }

    internal class IntentEnumConverter : JsonConverter<IntentEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(IntentEnum);

        public override IntentEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "edit":
                    return IntentEnum.Edit;
                case "update":
                    return IntentEnum.Update;
            }
            throw new Exception("Cannot unmarshal type IntentEnum");
        }

        public override void Write(Utf8JsonWriter writer, IntentEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case IntentEnum.Edit:
                    JsonSerializer.Serialize(writer, "edit", options);
                    return;
                case IntentEnum.Update:
                    JsonSerializer.Serialize(writer, "update", options);
                    return;
            }
            throw new Exception("Cannot marshal type IntentEnum");
        }

        public static readonly IntentEnumConverter Singleton = new IntentEnumConverter();
    }

    internal class FormatEnumConverter : JsonConverter<FormatEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(FormatEnum);

        public override FormatEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "gif":
                    return FormatEnum.Gif;
                case "jpeg":
                    return FormatEnum.Jpeg;
                case "png":
                    return FormatEnum.Png;
                case "tiff":
                    return FormatEnum.Tiff;
                case "webp":
                    return FormatEnum.Webp;
            }
            throw new Exception("Cannot unmarshal type FormatEnum");
        }

        public override void Write(Utf8JsonWriter writer, FormatEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case FormatEnum.Gif:
                    JsonSerializer.Serialize(writer, "gif", options);
                    return;
                case FormatEnum.Jpeg:
                    JsonSerializer.Serialize(writer, "jpeg", options);
                    return;
                case FormatEnum.Png:
                    JsonSerializer.Serialize(writer, "png", options);
                    return;
                case FormatEnum.Tiff:
                    JsonSerializer.Serialize(writer, "tiff", options);
                    return;
                case FormatEnum.Webp:
                    JsonSerializer.Serialize(writer, "webp", options);
                    return;
            }
            throw new Exception("Cannot marshal type FormatEnum");
        }

        public static readonly FormatEnumConverter Singleton = new FormatEnumConverter();
    }

    internal class QualityConverter : JsonConverter<Quality>
    {
        public override bool CanConvert(Type t) => t == typeof(Quality);

        public override Quality Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "high":
                    return Quality.High;
                case "low":
                    return Quality.Low;
                case "medium":
                    return Quality.Medium;
            }
            throw new Exception("Cannot unmarshal type Quality");
        }

        public override void Write(Utf8JsonWriter writer, Quality value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Quality.High:
                    JsonSerializer.Serialize(writer, "high", options);
                    return;
                case Quality.Low:
                    JsonSerializer.Serialize(writer, "low", options);
                    return;
                case Quality.Medium:
                    JsonSerializer.Serialize(writer, "medium", options);
                    return;
            }
            throw new Exception("Cannot marshal type Quality");
        }

        public static readonly QualityConverter Singleton = new QualityConverter();
    }

    internal class AlgConverter : JsonConverter<Alg>
    {
        public override bool CanConvert(Type t) => t == typeof(Alg);

        public override Alg Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Ed25519":
                    return Alg.Ed25519;
                case "Es256":
                    return Alg.Es256;
                case "Es384":
                    return Alg.Es384;
                case "Es512":
                    return Alg.Es512;
                case "Ps256":
                    return Alg.Ps256;
                case "Ps384":
                    return Alg.Ps384;
                case "Ps512":
                    return Alg.Ps512;
            }
            throw new Exception("Cannot unmarshal type Alg");
        }

        public override void Write(Utf8JsonWriter writer, Alg value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Alg.Ed25519:
                    JsonSerializer.Serialize(writer, "Ed25519", options);
                    return;
                case Alg.Es256:
                    JsonSerializer.Serialize(writer, "Es256", options);
                    return;
                case Alg.Es384:
                    JsonSerializer.Serialize(writer, "Es384", options);
                    return;
                case Alg.Es512:
                    JsonSerializer.Serialize(writer, "Es512", options);
                    return;
                case Alg.Ps256:
                    JsonSerializer.Serialize(writer, "Ps256", options);
                    return;
                case Alg.Ps384:
                    JsonSerializer.Serialize(writer, "Ps384", options);
                    return;
                case Alg.Ps512:
                    JsonSerializer.Serialize(writer, "Ps512", options);
                    return;
            }
            throw new Exception("Cannot marshal type Alg");
        }

        public static readonly AlgConverter Singleton = new AlgConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
