// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using ContentAuthenticity.Schema;
//
//    var c2PaStandardAssertionsSchema = C2PaStandardAssertionsSchema.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace ContentAuthenticity.Schema
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Schema-aligned DTO source for standard assertion payloads based on C2PA specification
    /// section 18.
    /// </summary>
    public partial class C2PaStandardAssertionsSchema
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.actions")]
        public ActionsAssertionV1 C2PaActions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.actions.v2")]
        public ActionsAssertionV2 C2PaActionsV2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.alternative-content-representation")]
        public AlternativeContentRepresentationAssertion C2PaAlternativeContentRepresentation { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.assertion.metadata")]
        public AssertionMetadataMap C2PaAssertionMetadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.asset-ref")]
        public AssetReferenceAssertion C2PaAssetRef { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.asset-type")]
        public AssetTypeAssertion C2PaAssetType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.asset-type.v2")]
        public AssetTypeAssertion C2PaAssetTypeV2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.certificate-status")]
        public CertificateStatusAssertion C2PaCertificateStatus { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.cloud-data")]
        public CloudDataAssertion C2PaCloudData { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.depthmap.GDepth")]
        public Dictionary<string, object> C2PaDepthmapGDepth { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.embedded-data")]
        public Dictionary<string, object> C2PaEmbeddedData { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.external-reference")]
        public ExternalReferenceAssertion C2PaExternalReference { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.bmff.v2")]
        public HashBmffAssertion C2PaHashBmffV2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.bmff.v3")]
        public HashBmffAssertion C2PaHashBmffV3 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.boxes")]
        public HashBoxesAssertion C2PaHashBoxes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.collection.data")]
        public HashCollectionDataAssertion C2PaHashCollectionData { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.data")]
        public HashDataAssertion C2PaHashData { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.hash.multi-asset")]
        public HashMultiAssetAssertion C2PaHashMultiAsset { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.ingredient")]
        public IngredientAssertionV1 C2PaIngredient { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.ingredient.v2")]
        public IngredientAssertionV2 C2PaIngredientV2 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.ingredient.v3")]
        public IngredientAssertionV3 C2PaIngredientV3 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.session-keys")]
        public Dictionary<string, object> C2PaSessionKeys { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.soft-binding")]
        public SoftBindingAssertion C2PaSoftBinding { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.thumbnail.claim")]
        public ThumbnailAssertion C2PaThumbnailClaim { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.thumbnail.ingredient")]
        public ThumbnailAssertion C2PaThumbnailIngredient { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa.time-stamp")]
        public Dictionary<string, string> C2PaTimeStamp { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("font.info")]
        public Dictionary<string, object> FontInfo { get; set; }
    }

    public partial class ActionsAssertionV1
    {
        [JsonPropertyName("actions")]
        public ActionItemV1[] Actions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }
    }

    public partial class ActionItemV1
    {
        [JsonPropertyName("action")]
        public string Action { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("changed")]
        public string Changed { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("digitalSourceType")]
        public string DigitalSourceType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instanceID")]
        public string InstanceId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("parameters")]
        public PurpleParameters Parameters { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgent")]
        public string SoftwareAgent { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("when")]
        public string When { get; set; }
    }

    public partial class PurpleParameters
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ingredient")]
        public HashedUriMap Ingredient { get; set; }
    }

    public partial class HashedUriMap
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonPropertyName("url")]
        public string Url { get; set; }
    }

    public partial class AssertionMetadataMap
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dataSource")]
        public DataSource DataSource { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dateTime")]
        public string DateTime { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("localizations")]
        public Dictionary<string, string>[] Localizations { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("reference")]
        public HashedUriMap Reference { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("regionOfInterest")]
        public Dictionary<string, object> RegionOfInterest { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("reviewRatings")]
        public ReviewRating[] ReviewRatings { get; set; }
    }

    public partial class DataSource
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("details")]
        public string Details { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    public partial class ReviewRating
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("explanation")]
        public string Explanation { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("value")]
        public long? Value { get; set; }
    }

    public partial class ActionsAssertionV2
    {
        [JsonPropertyName("actions")]
        public ActionItemV2[] Actions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("allActionsIncluded")]
        public bool? AllActionsIncluded { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgents")]
        public SoftwareAgent[] SoftwareAgents { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("templates")]
        public ActionTemplateV2[] Templates { get; set; }
    }

    public partial class ActionItemV2
    {
        [JsonPropertyName("action")]
        public string Action { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("changes")]
        public Dictionary<string, object>[] Changes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("digitalSourceType")]
        public string DigitalSourceType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("parameters")]
        public RelatedParameters Parameters { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("reason")]
        public string Reason { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("related")]
        public ActionItemV2[] Related { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgent")]
        public SoftwareAgent SoftwareAgent { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgentIndex")]
        public long? SoftwareAgentIndex { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("when")]
        public string When { get; set; }
    }

    public partial class RelatedParameters
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ingredients")]
        public HashedUriMap[] Ingredients { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("multipleInstances")]
        public bool? MultipleInstances { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("redacted")]
        public string Redacted { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sourceLanguage")]
        public string SourceLanguage { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("targetLanguage")]
        public string TargetLanguage { get; set; }
    }

    public partial class SoftwareAgent
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("icon")]
        public HashedUriMap Icon { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("operating_system")]
        public string OperatingSystem { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public partial class ActionTemplateV2
    {
        [JsonPropertyName("action")]
        public string Action { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("digitalSourceType")]
        public string DigitalSourceType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("icon")]
        public HashedUriMap Icon { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgent")]
        public SoftwareAgent SoftwareAgent { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softwareAgentIndex")]
        public long? SoftwareAgentIndex { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("templateParameters")]
        public Dictionary<string, object> TemplateParameters { get; set; }
    }

    public partial class AlternativeContentRepresentationAssertion
    {
        [JsonPropertyName("parameters")]
        public Dictionary<string, object> Parameters { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    public partial class AssetReferenceAssertion
    {
        [JsonPropertyName("references")]
        public ReferenceElement[] References { get; set; }
    }

    public partial class ReferenceElement
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonPropertyName("reference")]
        public ReferenceReference Reference { get; set; }
    }

    public partial class ReferenceReference
    {
        [JsonPropertyName("uri")]
        public string Uri { get; set; }
    }

    public partial class AssetTypeAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("types")]
        public TypeElement[] Types { get; set; }
    }

    public partial class TypeElement
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public partial class CertificateStatusAssertion
    {
        [JsonPropertyName("ocspVals")]
        public string[] OcspVals { get; set; }
    }

    public partial class CloudDataAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("content_type")]
        public string ContentType { get; set; }

        [JsonPropertyName("label")]
        public string Label { get; set; }

        [JsonPropertyName("location")]
        public HashedExtUriMap Location { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonPropertyName("size")]
        public long Size { get; set; }
    }

    public partial class HashedExtUriMap
    {
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data_types")]
        public Dictionary<string, object>[] DataTypes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("size")]
        public long? Size { get; set; }

        [JsonPropertyName("url")]
        public string Url { get; set; }
    }

    public partial class ExternalReferenceAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("label")]
        public string Label { get; set; }

        [JsonPropertyName("location")]
        public Location Location { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("size")]
        public long? Size { get; set; }
    }

    public partial class Location
    {
        [JsonPropertyName("content_type")]
        public string ContentType { get; set; }

        [JsonPropertyName("uri")]
        public string Uri { get; set; }
    }

    public partial class HashBmffAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonPropertyName("exclusions")]
        public Dictionary<string, object>[] Exclusions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("merkle")]
        public Dictionary<string, object>[] Merkle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sequenceNumber")]
        public long? SequenceNumber { get; set; }
    }

    public partial class HashBoxesAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonPropertyName("boxes")]
        public Box[] Boxes { get; set; }
    }

    public partial class Box
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("excluded")]
        public bool? Excluded { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exclusions")]
        public BoxExclusion[] Exclusions { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonPropertyName("names")]
        public string[] Names { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pad")]
        public string Pad { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pad2")]
        public string Pad2 { get; set; }
    }

    public partial class BoxExclusion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("boxIndex")]
        public long? BoxIndex { get; set; }

        [JsonPropertyName("length")]
        public long Length { get; set; }

        [JsonPropertyName("start")]
        public long Start { get; set; }
    }

    public partial class HashCollectionDataAssertion
    {
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonPropertyName("uris")]
        public Uris[] Uris { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("zip_central_directory_hash")]
        public string ZipCentralDirectoryHash { get; set; }
    }

    public partial class Uris
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data_types")]
        public Dictionary<string, object>[] DataTypes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("size")]
        public long? Size { get; set; }

        [JsonPropertyName("uri")]
        public string Uri { get; set; }
    }

    public partial class HashDataAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("exclusions")]
        public C2PaHashDataExclusion[] Exclusions { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("pad")]
        public string Pad { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pad2")]
        public string Pad2 { get; set; }
    }

    public partial class C2PaHashDataExclusion
    {
        [JsonPropertyName("length")]
        public long Length { get; set; }

        [JsonPropertyName("start")]
        public long Start { get; set; }
    }

    public partial class HashMultiAssetAssertion
    {
        [JsonPropertyName("parts")]
        public Part[] Parts { get; set; }
    }

    public partial class Part
    {
        [JsonPropertyName("hashAssertion")]
        public HashedUriMap HashAssertion { get; set; }

        [JsonPropertyName("location")]
        public Dictionary<string, object> Location { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("optional")]
        public bool? Optional { get; set; }
    }

    public partial class IngredientAssertionV1
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa_manifest")]
        public HashedUriMap C2PaManifest { get; set; }

        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonPropertyName("dc:title")]
        public string DcTitle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("documentID")]
        public string DocumentId { get; set; }

        [JsonPropertyName("instanceID")]
        public string InstanceId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonPropertyName("relationship")]
        public string Relationship { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("thumbnail")]
        public HashedUriMap Thumbnail { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("validationStatus")]
        public Dictionary<string, object>[] ValidationStatus { get; set; }
    }

    public partial class IngredientAssertionV2
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("c2pa_manifest")]
        public HashedUriMap C2PaManifest { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data")]
        public DataClass Data { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data_types")]
        public Dictionary<string, object>[] DataTypes { get; set; }

        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonPropertyName("dc:title")]
        public string DcTitle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("documentID")]
        public string DocumentId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("informational_URI")]
        public string InformationalUri { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instanceID")]
        public string InstanceId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonPropertyName("relationship")]
        public string Relationship { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("thumbnail")]
        public HashedUriMap Thumbnail { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("validationStatus")]
        public Dictionary<string, object>[] ValidationStatus { get; set; }
    }

    public partial class DataClass
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonPropertyName("url")]
        public string Url { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data_types")]
        public Dictionary<string, object>[] DataTypes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("size")]
        public long? Size { get; set; }
    }

    public partial class IngredientAssertionV3
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("activeManifest")]
        public HashedUriMap ActiveManifest { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("claimSignature")]
        public HashedUriMap ClaimSignature { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("data")]
        public DataClass Data { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dataTypes")]
        public Dictionary<string, object>[] DataTypes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:format")]
        public string DcFormat { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dc:title")]
        public string DcTitle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("informationalURI")]
        public string InformationalUri { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instanceID")]
        public string InstanceId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public AssertionMetadataMap Metadata { get; set; }

        [JsonPropertyName("relationship")]
        public string Relationship { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softBindingAlgorithmsMatched")]
        public string[] SoftBindingAlgorithmsMatched { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("softBindingsMatched")]
        public bool? SoftBindingsMatched { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("thumbnail")]
        public HashedUriMap Thumbnail { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("validationResults")]
        public Dictionary<string, object> ValidationResults { get; set; }
    }

    public partial class SoftBindingAssertion
    {
        [JsonPropertyName("alg")]
        public string Alg { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("alg-params")]
        public string AlgParams { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("bindingMetadata")]
        public Dictionary<string, object> BindingMetadata { get; set; }

        [JsonPropertyName("blocks")]
        public Block[] Blocks { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pad")]
        public string Pad { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pad2")]
        public string Pad2 { get; set; }
    }

    public partial class Block
    {
        [JsonPropertyName("scope")]
        public Dictionary<string, object> Scope { get; set; }

        [JsonPropertyName("value")]
        public string Value { get; set; }
    }

    public partial class ThumbnailAssertion
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("thumbnailType")]
        public long? ThumbnailType { get; set; }
    }

    public partial class C2PaStandardAssertionsSchema
    {
        public static C2PaStandardAssertionsSchema FromJson(string json) => JsonSerializer.Deserialize<C2PaStandardAssertionsSchema>(json, ContentAuthenticity.Schema.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this C2PaStandardAssertionsSchema self) => JsonSerializer.Serialize(self, ContentAuthenticity.Schema.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
